#!/bin/sh
#
# cheeseDOS - My x86 DOS
# Copyright (C) 2025  Connor Thomson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

CONFIG=build.conf

HDD_SIZE="512"

CC=clang
CVER=c99

LD=ld.lld

AS=nasm
FORMAT=bin

FLOPPY_SIZE=1474560

FLAGS="-ffreestanding \
       -Wall \
       -Wextra \
       -fno-stack-protector \
       -fno-builtin \
       -nostdinc \
       -std=$CVER \
       -pedantic \
       -fno-common \
       -pedantic-errors \
       -fno-pie"

LDFLAGS="-z noexecstack
         -nostdlib"

HDD="build/hdd.img"

SRC_DIR=src
BUILD_DIR=build

ELF="kernel.bin"
LINKER_SCRIPT="$SRC_DIR/link/link.ld"
OUTPUT="$BUILD_DIR/$ELF"

BOOT_DIR="$SRC_DIR/boot"
CPU_DIR="$SRC_DIR/cpu"

CONFIGURE_COUNT=0

check_dependencies() {
  required_tools="clang ld.lld nasm mkdir rm find basename dd sed printf test type exit cat sort wait"
  missing_tools=""

  for tool in $required_tools; do
    printf "Checking for %s..." "$tool"
    if type "$tool" > /dev/null 2>&1; then
      printf " Found!\n"
    else
      printf " Not Found!\n"
      if [ -z "$missing_tools" ]; then
        missing_tools="$tool"
      else
        missing_tools="$missing_tools $tool"
      fi
    fi
  done

  if [ -n "$missing_tools" ]; then
    printf "\n"
    printf "SOME TOOLS ARE NOT FOUND!"
    i=1
    for tool in $missing_tools; do
      printf "$i. $tool"
      i=$((i+1))
    done
    exit 1
  fi
}

get_includes() {
  includes=""
  for dir in $(find "$SRC_DIR" -type d | sort); do
    includes="$includes -I$dir"
  done
  printf "$includes"
}

INCLUDES=$(get_includes)

get_source_files() {
  find "$SRC_DIR" -name "*.c" -not -path "$BOOT_DIR/*" | sort
}

get_asm_files() {
  find "$SRC_DIR" -name "*.S" -not -path "$BOOT_DIR/*" | sort
}

get_object_files() {
  objs=""
  
  for src in $(get_source_files); do
    if [ -n "$src" ]; then
      basename_val=$(basename "$src" .c)
      obj="$BUILD_DIR/${basename_val}.o"
      if [ -z "$objs" ]; then
        objs="$obj"
      else
        objs="$objs $obj"
      fi
    fi
  done
  
  for src in $(get_asm_files); do
    if [ -n "$src" ]; then
      basename_val=$(basename "$src" .S)
      obj="$BUILD_DIR/${basename_val}.o"
      if [ -z "$objs" ]; then
        objs="$obj"
      else
        objs="$objs $obj"
      fi
    fi
  done
  
  printf "$objs"
}

build_c_object() {
  $CC $CFLAGS -c "$1" -o "$2"
}

build_asm_object() {
  $CC $ASMFLAGS -c "$1" -o "$2"
}

configure() {
    VALID_BITS="32 64"
    VALID_OPT="0 1 2 3 fast s"
    VALID_SUDO="sudo doas"

    BITS=32
    MARCH=i386
    OPT=fast
    FLOPPY=cheeseDOS.img
    SU=sudo

    for arg in "$@"; do
        case $arg in
            --bits=*)
                BITS="${arg#*=}"
                echo "$VALID_BITS" | grep -qw "$BITS" || { echo "Invalid --bits=$BITS"; exit 1; }
                ;;
            --march=*)
                MARCH="${arg#*=}"
                ;;
            --optimize=*)
                OPT="${arg#*=}"
                echo "$VALID_OPT" | grep -qw "$OPT" || { echo "Invalid --optimize=$OPT"; exit 1; }
                ;;
            --floppy=*)
                FLOPPY="${arg#*=}"
                ;;
            --sudo=*)
                SU="${arg#*=}"
                echo "$VALID_SUDO" | grep -qw "$SU" || { echo "Invalid --sudo=$SU"; exit 1; }
                ;;
            *)
                echo "Unknown option: $arg"
                exit 1
                ;;
        esac
    done

    cat <<EOF > $CONFIG
# Auto-generated by configure.sh

BITS=$BITS
MARCH=$MARCH
OPT=$OPT
FLOPPY=$FLOPPY
SUDO=$SU
EOF

    CONFIGURE_COUNT=$((CONFIGURE_COUNT + 1))

    printf "Configured cheeseDOS with:\n" "$CONFIGURE_COUNT"
    printf "  BITS=$BITS\n"
    printf "  MARCH=$MARCH\n"
    printf "  OPT=$OPT\n"
    printf "  FLOPPY=$FLOPPY\n"
    printf "  SUDO=$SU\n"

    return 0
}

SCRIPT_ARGS=""

check_config() {
    has_config_option=0
    for arg in $SCRIPT_ARGS; do
        case "$arg" in
            --bits=*|--march=*|--optimize=*|--floppy=*|--sudo=*)
                has_config_option=1
                break
                ;;
        esac
    done
    
    if [ "$CONFIGURE_COUNT" -eq 0 ]; then
        if [ ! -f "$CONFIG" ] || [ "$has_config_option" -eq 1 ]; then
            configure $SCRIPT_ARGS || exit 1
        fi
    fi

    BITS=$(sed -n 's/^BITS=//p' "$CONFIG")
    MARCH=$(sed -n 's/^MARCH=//p' "$CONFIG")
    OPT=$(sed -n 's/^OPT=//p' "$CONFIG")
    FLOPPY=$(sed -n 's/^FLOPPY=//p' "$CONFIG")
    SUDO=$(sed -n 's/^SUDO=//p' "$CONFIG")
   
    return 0
}

all() {
  check_dependencies
  
  check_config

  clean

  printf "Making directory: %s..." "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"
  printf " Done!\n"

  build_pids=""

  CFLAGS="-m$BITS \
        -march=$MARCH \
        -O$OPT \
        -mtune=$MARCH \
        -g$GDBINFO \
        $FLAGS \
        $INCLUDES"

  ASMFLAGS="-m$BITS \
          $INCLUDES"

  build_c() {
    src="$1"
    obj="$2"
    log="$BUILD_DIR/$(basename "$obj").log"

    printf "Compiling %s... Done!\n" "$(basename "$obj")"

    {
	if build_c_object "$src" "$obj" >"$log" 2>&1; then
            rm -f "$log"
	else
            cat "$log"
            rm -f "$log"
            exit 1
	fi
    } &
    build_pids="$build_pids $!"
  }
  
  build_asm() {
    src="$1"
    obj="$2"
    log="$BUILD_DIR/$(basename "$obj").log"

    printf "Assembling %s...\n" "$(basename "$obj")"

    {
	if build_asm_object "$src" "$obj" >"$log" 2>&1; then
            rm -f "$log"
        else
            cat "$log"
            rm -f "$log"
            exit 1
	fi
    } &
    build_pids="$build_pids $!"
  }

  for src in $(get_source_files); do
    if [ -n "$src" ]; then
      basename_val=$(basename "$src" .c)
      obj="$BUILD_DIR/${basename_val}.o"
      build_c "$src" "$obj"
    fi
  done
  
  for src in $(get_asm_files); do
    if [ -n "$src" ]; then
      basename_val=$(basename "$src" .S)
      obj="$BUILD_DIR/${basename_val}.o"
      build_asm "$src" "$obj"
    fi
  done

  for pid in $build_pids; do
    wait "$pid"
  done

  printf "Assembling stage1.bin..."
    $AS -f $FORMAT -o "$BUILD_DIR/stage1.bin" "$BOOT_DIR/stage1.asm"
  printf " Done!\n"

  printf "Assembling stage2.bin..."
    $AS -f $FORMAT -o "$BUILD_DIR/stage2.bin" "$BOOT_DIR/stage2.asm"
  printf " Done!\n"

  OBJS=$(get_object_files)
  
  obj_count=0
  for obj in $OBJS; do
    obj_count=$((obj_count + 1))
  done

  printf "Linking %d objects to %s..." "$obj_count" "$(basename $OUTPUT)"
    $LD -T $LINKER_SCRIPT -o $OUTPUT $OBJS
  printf " Done!\n"

  printf "Adding stage1.bin to %s..." "$FLOPPY"
    dd if=$BUILD_DIR/stage1.bin of=$FLOPPY bs=512 seek=0 conv=notrunc >/dev/null 2>&1
  printf " Done!\n"

  printf "Adding stage2.bin to %s..." "$FLOPPY"
    dd if=$BUILD_DIR/stage2.bin of=$FLOPPY bs=512 seek=1 conv=notrunc >/dev/null 2>&1
  printf " Done!\n"

  printf "Adding %s to %s..." "$ELF" "$FLOPPY"
    dd if=$OUTPUT of=$FLOPPY bs=512 seek=3 conv=notrunc >/dev/null 2>&1
  printf " Done!\n"

  printf "Padding %s..." "$FLOPPY"
    dd if=/dev/zero of=$FLOPPY bs=1 count=0 seek=$FLOPPY_SIZE 2>/dev/null
  printf " Done!\n"

  exit 0
}

make_hdd_image() {
  printf "Creating %sB disk image to %s..." "$HDD_SIZE" "$HDD"
    dd if=/dev/zero of="$HDD" bs="$HDD_SIZE" count=1 \
      > /dev/null 2>&1
  printf " Done!\n"
}

MEM=1M
CPU=486
CPU_FLAGS="-fpu,-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2"

run() {
  check_config

  if [ ! -f "$FLOPPY" ]; then
    printf "Error: Floppy image $FLOPPY not found. Run 'build' first.\n"
    exit 1
  fi
  
  if [ ! -f "$HDD" ]; then
    make_hdd_image
  fi

  qemu-system-i386 \
    -audiodev pa,id=snd0 \
    -machine pcspk-audiodev=snd0 \
    -serial stdio \
    -display gtk \
    -drive file="$FLOPPY",format=raw,if=floppy \
    -m "$MEM" \
    -cpu "$CPU","$CPU_FLAGS" \
    -vga std \
    -chardev vc,id=mon0 \
    -mon chardev=mon0,mode=readline \
    -rtc base=localtime \
    -nodefaults \
    -drive file="$HDD",format=raw,if=ide,media=disk
}

run_kvm() {
  check_config

  if [ ! -f "$FLOPPY" ]; then
    printf "Error: Floppy image $FLOPPY not found. Run 'build' first.\n"
    exit 1
  fi
  
  if [ ! -f "$HDD" ]; then
    make_hdd_image
  fi

  qemu-system-i386 \
    -audiodev pa,id=snd0 \
    -machine pcspk-audiodev=snd0 \
    -serial stdio \
    -display gtk \
    -drive file="$FLOPPY",format=raw,if=floppy \
    -m "$MEM" \
    -cpu "$CPU","$CPU_FLAGS" \
    -vga std \
    -chardev vc,id=mon0 \
    -mon chardev=mon0,mode=readline \
    -rtc base=localtime \
    -nodefaults \
    -drive file="$HDD",format=raw,if=ide,media=disk \
    -enable-kvm
}

clean() {
  check_config
  printf "Cleaning up..."
    rm -rf "$BUILD_DIR" "$FLOPPY"
  printf " Done!\n"
}

run_gdb() {
  check_config

  if [ ! -f "$FLOPPY" ]; then
    printf "Error: Floppy image $FLOPPY not found. Run 'build' first.\n"
    exit 1
  fi
  
  if [ ! -f "$HDD" ]; then
    make_hdd_image
  fi

  qemu-system-i386 \
    -audiodev pa,id=snd0 \
    -machine pcspk-audiodev=snd0 \
    -serial stdio \
    -display gtk \
    -drive file="$FLOPPY",format=raw,if=floppy \
    -m "$MEM" \
    -cpu "$CPU","$CPU_FLAGS" \
    -vga std \
    -chardev vc,id=mon0 \
    -mon chardev=mon0,mode=readline \
    -rtc base=localtime \
    -nodefaults \
    -drive file="$HDD",format=raw,if=ide,media=disk \
    -s \
    -S
}

run_kvm_gdb() {
  check_config

  if [ ! -f "$FLOPPY" ]; then
    printf "Error: Floppy image $FLOPPY not found. Run 'build' first.\n"
    exit 1
  fi
  
  if [ ! -f "$HDD" ]; then
    make_hdd_image
  fi

  qemu-system-i386 \
    -audiodev pa,id=snd0 \
    -machine pcspk-audiodev=snd0 \
    -serial stdio \
    -display gtk \
    -drive file="$FLOPPY",format=raw,if=floppy \
    -m "$MEM" \
    -cpu "$CPU","$CPU_FLAGS" \
    -vga std \
    -chardev vc,id=mon0 \
    -mon chardev=mon0,mode=readline \
    -rtc base=localtime \
    -nodefaults \
    -drive file="$HDD",format=raw,if=ide,media=disk \
    -enable-kvm \
    -s \
    -S
}

distclean() {
  printf "Cleaning up..."
    rm -rf "$BUILD_DIR" "$FLOPPY" "build.conf"
  printf " Done!\n"
}

docs() {
  rm -rf docs
  git clone --depth=1 https://github.com/The-cheeseDOS-Project/docs
}

if [ $# -eq 0 ]; then
  CMD=""
  SCRIPT_ARGS=""
else
  CMD="$1"
  case "$CMD" in
    --*)
      CMD=""
      SCRIPT_ARGS="$@"
      ;;
    *)
      shift
      SCRIPT_ARGS="$@"
      ;;
  esac
fi

case "$CMD" in
  "") all ;;
  all) all ;;
  run) run ;;
  run-kvm) run_kvm ;;
  run-gdb) run_gdb ;;
  run-kvm-gdb) run_kvm_gdb ;;
  clean) clean ;;
  distclean) distclean ;;
  docs) docs ;;
  *) printf "Usage: $0 {all|run|run-kvm|run-gdb|run-kvm-gdb|clean|docs|distclean|docs}\n" ; exit 1 ;;
esac
