#!/bin/sh
#
# cheeseDOS - My x86 DOS
# Copyright (C) 2025  Connor Thomson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

CONFIG=config.conf

VALID_BITS="32 64"
VALID_MARCH="i386 i486 i586 i686 pentium pentium-mmx pentiumpro pentium2 pentium3 pentium4 prescott nocona core2 nehalem westmere sandybridge ivybridge haswell broadwell skylake cannonlake icelake-client icelake-server tigerlake rocketlake alderlake sapphirerapids meteorlake emeraldrapids graniterapids-d arrowlake lunarlake pantherlake siliconrapids clearlake"
VALID_OPT="0 1 2 3 fast s g z"
VALID_GDBINFO="0 1 2 3"
VALID_STRIP="true false"
VALID_SUDO="sudo doas"

BITS=32
MARCH=i386
OPT=s
GDBINFO=0
STRIP=true
FLOPPY=cheeseDOS.img
SU=sudo

for arg in "$@"; do
  case $arg in
    --bits=*)
      BITS="${arg#*=}"
      echo "$VALID_BITS" | grep -qw "$BITS" || { echo "Invalid --bits=$BITS"; exit 1; }
      ;;
    --march=*)
      MARCH="${arg#*=}"
      echo "$VALID_MARCH" | grep -qw "$MARCH" || { echo "Invalid --march=$MARCH"; exit 1; }
      ;;
    --optimize=*)
      OPT="${arg#*=}"
      echo "$VALID_OPT" | grep -qw "$OPT" || { echo "Invalid --optimize=$OPT"; exit 1; }
      ;;
    --debug-info=*)
      GDBINFO="${arg#*=}"
      echo "$VALID_GDBINFO" | grep -qw "$GDBINFO" || { echo "Invalid --debug-info=$GDBINFO"; exit 1; }
      ;;
    --strip=*)
      STRIP="${arg#*=}"
      echo "$VALID_STRIP" | grep -qw "$STRIP" || { echo "Invalid --strip=$STRIP"; exit 1; }
      ;;
    --floppy=*)
      FLOPPY="${arg#*=}"
      ;;
    --sudo=*)
      SU="${arg#*=}"
      echo "$VALID_SUDO" | grep -qw "$SU" || { echo "Invalid --sudo=$SU"; exit 1; }
      ;;
    *)
      echo "Unknown option: $arg"
      exit 1
      ;;
  esac
done

cat <<EOF > $CONFIG
# Auto-generated by configure.sh

BITS=$BITS
MARCH=$MARCH
OPT=$OPT
GDBINFO=$GDBINFO
STRIP=$STRIP
FLOPPY=$FLOPPY
SU=$SU
EOF

echo "Configured cheeseDOS with:"
echo "  BITS=$BITS"
echo "  MARCH=$MARCH"
echo "  OPT=$OPT"
echo "  GDBINFO=$GDBINFO"
echo "  STRIP=$STRIP"
echo "  FLOPPY=$FLOPPY"
echo "  SUDO=$SU"
