/*
 * cheeseDOS - My x86 DOS
 * Copyright (C) 2025  Connor Thomson
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <stdio.h>
#include <string.h>

#define CONFIG_FILE "config.conf"
#define DEFAULT_BITS "32"
#define DEFAULT_MARCH "i386"
#define DEFAULT_OPT "s"
#define DEFAULT_FLOPPY "cheeseDOS.img"
#define DEFAULT_SU "sudo"

const char *VALID_BITS[] = {"32", "64"};
const char *VALID_OPT[] = {"0", "1", "2", "3", "fast", "s"};
const char *VALID_SUDO[] = {"sudo", "doas"};

int is_valid(const char *value, const char *valid[], int count) {
    for (int i = 0; i < count; i++) {
        if (strcmp(value, valid[i]) == 0) return 1;
    }
    return 0;
}

int main(int argc, char *argv[]) {
    const char *BITS = DEFAULT_BITS;
    const char *MARCH = DEFAULT_MARCH;
    const char *OPT = DEFAULT_OPT;
    const char *FLOPPY = DEFAULT_FLOPPY;
    const char *SU = DEFAULT_SU;

    for (int i = 1; i < argc; i++) {
        if (strncmp(argv[i], "--bits=", 7) == 0) {
            BITS = argv[i] + 7;
            if (!is_valid(BITS, VALID_BITS, 2)) {
                printf("Invalid --bits=%s\n", BITS);
                return 1;
            }
        } else if (strncmp(argv[i], "--march=", 8) == 0) {
            MARCH = argv[i] + 8;
        } else if (strncmp(argv[i], "--optimize=", 11) == 0) {
            OPT = argv[i] + 11;
            if (!is_valid(OPT, VALID_OPT, 6)) {
                printf("Invalid --optimize=%s\n", OPT);
                return 1;
            }
        } else if (strncmp(argv[i], "--floppy=", 9) == 0) {
            FLOPPY = argv[i] + 9;
        } else if (strncmp(argv[i], "--sudo=", 8) == 0) {
            SU = argv[i] + 8;
            if (!is_valid(SU, VALID_SUDO, 2)) {
                printf("Invalid --sudo=%s\n", SU);
                return 1;
            }
        } else {
            printf("Unknown option: %s\n", argv[i]);
            return 1;
        }
    }

    FILE *f = fopen(CONFIG_FILE, "w");
    if (!f) {
        printf("Failed to write %s\n", CONFIG_FILE);
        return 1;
    }

    fprintf(f, "# Auto-generated by configure.c\n\n");
    fprintf(f, "BITS=%s\n", BITS);
    fprintf(f, "MARCH=%s\n", MARCH);
    fprintf(f, "OPT=%s\n", OPT);
    fprintf(f, "FLOPPY=%s\n", FLOPPY);
    fprintf(f, "SU=%s\n", SU);
    fclose(f);

    printf("Configured cheeseDOS with:\n");
    printf("  BITS=%s\n", BITS);
    printf("  MARCH=%s\n", MARCH);
    printf("  OPT=%s\n", OPT);
    printf("  FLOPPY=%s\n", FLOPPY);
    printf("  SUDO=%s\n", SU);

    return 0;
}
