#!/bin/sh
#
# cheeseDOS - My x86 DOS
# Copyright (C) 2025  Connor Thomson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Config file
CONFIG=config.conf

# Valid options
VALID_BITS="32 64"
VALID_OPT="0 1 2 3 fast s"
VALID_SUDO="sudo doas"

# Presets
BITS=32
MARCH=i386
OPT=s
FLOPPY=cheeseDOS.img
SU=sudo

for arg in "$@"; do
  case $arg in
    --bits=*)
      BITS="${arg#*=}"
      echo "$VALID_BITS" | grep -qw "$BITS" || { echo "Invalid --bits=$BITS"; exit 1; } # Check if valid, if so, put it into config file
      ;;
    --march=*)
      MARCH="${arg#*=}" # Put into config file
      ;;
    --optimize=*)
      OPT="${arg#*=}"
      echo "$VALID_OPT" | grep -qw "$OPT" || { echo "Invalid --optimize=$OPT"; exit 1; } # Check if valid, if so, put it into config file
      ;;
    --floppy=*)
      FLOPPY="${arg#*=}" # Put into config file
      ;;
    --sudo=*)
      SU="${arg#*=}"
      echo "$VALID_SUDO" | grep -qw "$SU" || { echo "Invalid --sudo=$SU"; exit 1; } # Check if valid, if so, put it into config file
      ;;
    *)
      echo "Unknown option: $arg"
      exit 1
      ;;
  esac
done

cat <<EOF > $CONFIG
# Auto-generated by configure.sh

BITS=$BITS
MARCH=$MARCH
OPT=$OPT
FLOPPY=$FLOPPY
SU=$SU
EOF

echo "Configured cheeseDOS with:"
echo "  BITS=$BITS"
echo "  MARCH=$MARCH"
echo "  OPT=$OPT"
echo "  FLOPPY=$FLOPPY"
echo "  SUDO=$SU"
