# cheeseDOS - My x86 DOS
# Copyright (C) 2025  Connor Thomson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: Build and Release cheeseDOS
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.sh'
      - '.github/workflows/**'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      TZ: America/Los_Angeles
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Correct time
        run: |
          sudo timedatectl set-timezone America/Los_Angeles
          sudo timedatectl set-ntp true
      
      - name: Append changelog to release.md
        run: |
          echo "" >> .github/release.md
          echo "## Changelog" >> .github/release.md
          
          CURRENT_COMMIT=$(git rev-parse HEAD)
          PREV_COMMIT=$(git rev-parse HEAD~1 2>/dev/null || echo "")
          
          if [ -n "$PREV_COMMIT" ]; then
            echo "Comparing $PREV_COMMIT..$CURRENT_COMMIT"
            CHANGED_FILES=$(git diff --name-only $PREV_COMMIT..$CURRENT_COMMIT)
            COMMIT_MSG=$(git log -1 --pretty=format:"%s" $CURRENT_COMMIT)
            
            if [ -n "$CHANGED_FILES" ]; then
              echo "$CHANGED_FILES" | while read -r file; do
                if [ -n "$file" ]; then
                  echo "- \`$file\`: $COMMIT_MSG" >> .github/release.md
                fi
              done
            else
              echo "- No files changed in this commit" >> .github/release.md
            fi
          else
            COMMIT_MSG=$(git log -1 --pretty=format:"%s")
            echo "- Initial commit: $COMMIT_MSG" >> .github/release.md
            find src/ -type f | head -10 | while read -r file; do
              echo "- \`$file\`: $COMMIT_MSG" >> .github/release.md
            done
          fi
          
      - name: Generate timestamp
        run: |
          DATE=$(date +"%m%d%y%H%M")
          echo -n "a$DATE" > src/version/version.txt
      
      - name: Commit version.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/version/version.txt
          git commit -m "Update version.txt to $(cat src/version/version.txt)"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build cheeseDOS
        run: |
          chmod +x ./build.sh
          ./build.sh all --no-dep-check
      
      # - name: Upload ISO artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: cheeseDOS-iso
      #     path: cheesedos-cdrom.iso
      
      - name: Upload IMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: cheeseDOS-img
          path: cdos-1.44mb-floppy.img
      
      - name: Read version tag
        id: readtag
        run: |
          TAG=$(cat src/version/version.txt)
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      
      - name: Create GitHub Release and Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ steps.readtag.outputs.tag }}"
          TITLE="cheeseDOS alpha (build: $TAG)"
          gh release create "$TAG" cdos-1.44mb-floppy.img --title "$TITLE" --notes-file .github/release.md
